import type { Metadata } from "next";
import "../styles/globals.css";
import { WeatherProvider } from "@/contexts/weatherCtx";

export const metadata: Metadata = {
  title: "WheatherShine",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-neutral-900">
        <WeatherProvider>{children}</WeatherProvider>
      </body>
    </html>
  );
}
