import type { Metadata } from "next";
import "../styles/globals.css";
import { WeatherProvider } from "@/contexts/weatherCtx";
import { AirPollutionProvider } from "@/contexts/airCtx";
import { ForecastProvider } from "@/contexts/forecastCtx";

export const metadata: Metadata = {
  title: "WheatherShine",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-neutral-900">
        <WeatherProvider>
          <ForecastProvider>
            <AirPollutionProvider>{children}</AirPollutionProvider>
          </ForecastProvider>
        </WeatherProvider>
      </body>
    </html>
  );
}
